### ISSUE TITLE
use find

### ISSUE THREAD

**Issue by muescha** [kapilgorve/personal-website#7]
you can use the [Array#find](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

```javascript 
var node = posts.find(post => post.id === id)
```

https://github.com/kapilgorve/personal-website/blob/1bad20c7875e4dda21adc9e1e58233b452f80396/src/pages/details/index.js#L16-L22

**Comment by kapilgorve** [comment]
Thanks.  Using array.find now .
